# Generated by Django 5.0.4 on 2024-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, to='store.star'),
        ),
    ]
