# Generated by Django 5.0.4 on 2024-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_movie_stars_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='movies', to='store.star'),
        ),
    ]
