# Generated by Django 5.0.4 on 2024-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_movie_likes_alter_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
